### PR TITLE
Bumbed some dependencies, works on node 17.3

### LINKED ISSUE #173: coa dependency seems broken
```
/home/flip111/javascript/html-differ/node_modules/coa/lib/cmd.js:243
        UTIL.error(msg);
             ^

TypeError: UTIL.error is not a function
    at process.<anonymous> (/home/flip111/javascript/html-differ/node_modules/coa/lib/cmd.js:243:14)
    at Object.onceWrapper (node:events:510:26)
    at process.emit (node:events:390:28)

Node.js v17.3.0
```

### PR DESCRIPTION
**Pull request by flip111**
fixes https://github.com/bem/html-differ/issues/173

### CODE REVIEW

**Comment by HaimCandiTech** [comment]
This also fixes two high security vulnerabilities that are found in 'diff' package

@tadatuta 
Any chance this can get in?

image
